### ISSUE TITLE
is it posible to be compatible with dopus? Directory Opus

### ISSUE THREAD

**Issue by Warden20** [Flow-Launcher/Flow.Launcher.Plugin.Everything#10]
When I open folders the plugin only uses the normal file explorer from windows 10

**Comment by jjw24** [comment]
have you tried with customised explorer option in Everything's settings page?

**Comment by kubalav** [comment]
I tried to use plugin with Directory Opus (customized explorer) and it's working as expected.

**Comment by jjw24** [comment]
Awesome, thank you for letting me know @kubalav
