### ISSUE TITLE
Plugin language doesn't match with Flow Launcher language after plugin update

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher.Plugin.Everything#11]
Plugin language switch to English after plugin update. I'm not sure it's related to Everything plugin only.

**Comment by jjw24** [comment]
Thanks for letting us know, will get it fixed soon. It's related to Everything plugin only.

**Comment by jjw24** [comment]
the latest Everything release should fix this problem. Let me know if otherwise

**Comment by kubalav** [comment]
I have 1.4.0 version. I see GitHub release 1.4.1, but Plugin manager says: "All plugins are up to date."

**Comment by jjw24** [comment]
hmm github's auto merge didnt trigger for some reason. try reload plugin data now, you should get the update

**Comment by kubalav** [comment]
It's working now. Thank you @jjw24.
