### ISSUE TITLE
Can not found Everything

### ISSUE THREAD

**Issue by aukaheng** [Flow-Launcher/Flow.Launcher.Plugin.Everything#13]
I have installed Everything through `scoop`, and configure it to run as a Windows service.
The plugin seems not able to locate it.

**Comment by jjw24** [comment]
can you check for me in your registry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
 if there is a key called Everything, and a subkey called DisplayName which contains a string something like "Everything 1.3.4.686 (x64)"
This is how Everything Plugin identifies if it is installed

if you cant find it there, do you know where scoop would install it in the registry?

**Comment by aukaheng** [comment]
I don't have that key in my registry 😅
Maybe it is because `scoop` is using the **portable** version of Everything.

Ignoring the warning, the searching does indeed work.

But if I use the "Open with notepad" action, it'll complaint about `"{path}" not found`.

**Comment by jjw24** [comment]
>But if I use the "Open with notepad" action, it'll complaint about "{path}" not found.

something like this?
![image](https://user-images.githubusercontent.com/26427004/106866890-193de300-6721-11eb-858c-32d9aacf0e16.png)

**Comment by jjw24** [comment]
> Maybe it is because scoop is using the portable version of Everything.

do you know where scoop installs Everything to?

**Comment by aukaheng** [comment]
> 
> 
> > But if I use the "Open with notepad" action, it'll complaint about "{path}" not found.
> 
> something like this?
> ![image](https://user-images.githubusercontent.com/26427004/106866890-193de300-6721-11eb-858c-32d9aacf0e16.png)

Yes, very similar.
![image](https://user-images.githubusercontent.com/2141915/106868129-5eeeb180-6709-11eb-9c00-e0e2099d7f82.png)

**Comment by aukaheng** [comment]
> 
> 
> > Maybe it is because scoop is using the portable version of Everything.
> 
> do you know where scoop installs Everything to?

Under `C:\Users\{username}\scoop\apps\everything\current\Everything.exe`.

**Comment by jjw24** [comment]
try this build from #14 , should no longer display that warning or ask you to install Everything:
[Flow.Launcher.Plugin.Everything.zip](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/files/5924521/Flow.Launcher.Plugin.Everything.zip)

extract it to your userdata folder under plugins.
