### ISSUE TITLE
open with custom editor does not work

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher.Plugin.Everything#15]
set custom editor path from Everything settings

find a file and open

will complain:
![image](https://user-images.githubusercontent.com/26427004/106873325-725d4500-6728-11eb-92c3-dcaf34f40307.png)

from #13

**Comment by jjw24** [comment]
possibly how it handles the path here, from main.cs:
![image](https://user-images.githubusercontent.com/26427004/106873566-b51f1d00-6728-11eb-94a5-edaa722e6f23.png)

**Comment by taooceros** [comment]
I am quite busy these few days...... This should be an easy fix, so once I finish up my stuff, I will try to fix it.
