### ISSUE TITLE
"Open parent folder" didn't work as expected

### ISSUE THREAD

**Issue by aukaheng** [Flow-Launcher/Flow.Launcher.Plugin.Everything#21]
It actually **opens** the file instead of opening the **folder** where the file is stored.

**Comment by taooceros** [comment]
Will take a look now

**Comment by taooceros** [comment]
Found the issue. a "/" is missed on the default argument....
Sorry for the inconvience.😅

**Comment by kubalav** [comment]
Is it working? It opens 2 level lower like expected.
Path
C:\Program Files\Total Commander\mmedia.ini
it opens C:\
path
E:\Download\TEST\Sandbox Apps\totalcmd\mmedia.ini
it opens E:\Download\TEST\

**Comment by taooceros** [comment]
Are you using explorer or customized explorer?

**Comment by kubalav** [comment]
Customized explorer (Total Commander)

**Comment by taooceros** [comment]
> Customized explorer (Total Commander)

If that's the case, this build won't have effect on it since it only changes the default argument for explorer. Which args are you using? %s?

**Comment by kubalav** [comment]
I use %s.

**Comment by taooceros** [comment]
I will take a look now.

**Comment by taooceros** [comment]
Werid, I test the latest version of everything plugin, and %s works as intended in my computer……
Are your args only contain "%s" or "/O %s"? Because I don't have TC so I can only test it with another customized explorer

**Comment by kubalav** [comment]
%s only

**Comment by taooceros** [comment]
Oh maybe the issue is we don't include "" around the path, so it is splitted because of space. I will add one, and you can take a try.

**Comment by kubalav** [comment]
It is weird. Some files are working. Path file containing space don't working. Quotation mark will be fix it.

**Comment by taooceros** [comment]
[Flow.Launcher.Plugin.Everything.zip](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Everything/files/5964404/Flow.Launcher.Plugin.Everything.zip)
Take a try @kubalav

**Comment by kubalav** [comment]
It's working now. Thank you @taooceros

**Comment by taooceros** [comment]
Great! I will create a new pr regarding that change.
