### ISSUE TITLE
How Should run the project? 

### ISSUE THREAD

**Issue by babakmdi** [Flow-Launcher/Flow.Launcher.Plugin.Everything#39]

**Comment by jjw24** [comment]
Hi @babakmdi , do you mean how to use the plugin? you use it via [flow launcher](https://github.com/Flow-Launcher/Flow.Launcher). Once installed, then type `pm install everything`.

Feel free to reopen this issue if you have anymore questions.

**Comment by babakmdi** [comment]
![image](https://user-images.githubusercontent.com/65450661/142077343-5895112c-405e-450c-8f7f-832172b0d300.png)
i get this error

iam using .net core5

![image](https://user-images.githubusercontent.com/65450661/142077447-7e89a6cc-89d4-4ce1-adb8-3d9b71f48daf.png)

**Comment by jjw24** [comment]
hey how's it going. I am assuming you have changed anything yet and branched off current dev right?

Which windows are you running this on?

Maybe try rebuilding a couple of times
 
which .Net 5 sdk version have you got installed?
![image](https://user-images.githubusercontent.com/26427004/142270580-9129c817-e1f4-4297-96dc-82f08aad2ccf.png)

also can you set the startup project to Flow.Launcher:
![image](https://user-images.githubusercontent.com/26427004/142271060-a6735d0f-5b9d-4b93-a2b8-a74c836d8b63.png)

**Comment by babakmdi** [comment]
Hello I Download The Project And Just Run It ,  Iam Using Windows 10 , iam using this version of .net core "  5.0.403 ".

**Comment by babakmdi** [comment]
![akdnsjnkssjknkdsnk](https://user-images.githubusercontent.com/65450661/142661467-9395831e-ea3a-4d2b-9a41-dd162db256ff.png)


![image](https://user-images.githubusercontent.com/65450661/142661181-63754ff7-7b78-421c-b924-63c477828cbe.png)


should i do anything else?

**Comment by jjw24** [comment]
yeah looks all correct configuration wise. I think maybe the the .net version? can you try the version 5.1 or my version.

Assuming this is the only .Net project you have, can you try deleting the folders inside this nuget folder here (delete as much as you can):
%userprofile%\.nuget\packages\

this folder contains the libraries needed for .net projects, clearing it and try rebuild the solution a couple of times. Let me know how you go.
![image](https://user-images.githubusercontent.com/26427004/142717887-7ecc0ae3-b756-493c-a2a8-9afeef1b06e1.png)

**Comment by jjw24** [comment]
hey @babakmdi , have you got it working?

**Comment by jjw24** [comment]
Closing. Please re-open if still having issue.
