### ISSUE TITLE
Add custom Everything macros to Flow Launcher plugin

### ISSUE THREAD

**Issue by ghost** [Flow-Launcher/Flow.Launcher.Plugin.Everything#40]
In the Everything application, it is possible to create a custom macro that activates a certain filter e.g.
`myHome:` could activate a filter that only looks for files under the user's home path. 

Unfortunately, these custom macros created in the main Everything application do not become available in the everything plugin. Would it be possible to add this functionality?

**Comment by taooceros** [comment]
I check that. It works?
![image](https://user-images.githubusercontent.com/45326534/156937697-23f024d1-bfdc-40ef-b8be-3a9b97ebacaa.png)

**Comment by jjw24** [comment]
Hi there, we have merged Everything plugin with the Explorer plugin, please update to the latest version of Flow and remove the standalone Everything plugin via `pm uninstall Everything`.

If this request is still required, please open an issue in the main [Flow project](https://github.com/Flow-Launcher/Flow.Launcher).
