### ISSUE TITLE
"CTRL ENTER"shortcut to open the parent folder

### ISSUE THREAD

**Issue by fanhwid** [Flow-Launcher/Flow.Launcher.Plugin.Everything#44]
Consider add a shortcut to open the selected result parent folder, like "CTRL ENTER".

**Comment by hahaleyile** [comment]
It seams like [explorer plugin](https://github.com/Flow-Launcher/Flow.Launcher/blob/472fff83fd91affe51dcf9d5809676e13671df6d/Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs#L132) have implemented the hot key function, so maybe add the function here would not be the problem.

**Comment by taooceros** [comment]
Somehow we are drafting to merge explorer and everything plugin, so we are not focus on the development of everything plugin for now. Though, feel free to implement the feature and fire a pr, which should be fairly simple.

**Comment by hahaleyile** [comment]
> Somehow we are drafting to merge explorer and everything plugin, so we are not focus on the development of everything plugin for now. Though, feel free to implement the feature and fire a pr, which should be fairly simple.

Okay, I get it.

**Comment by jjw24** [comment]
Hi there, we have merged Everything plugin with the Explorer plugin, please update to the latest version of Flow and remove the standalone Everything plugin via `pm uninstall Everything`.

If this issue still persists, please open an issue in the main [Flow project](https://github.com/Flow-Launcher/Flow.Launcher).
