### ISSUE TITLE
Search Results are not as expected

### ISSUE THREAD

**Issue by guntern** [Flow-Launcher/Flow.Launcher.Plugin.Everything#45]
I had this issue already some times, but was always able to work around it. But this time not. The search results from the Everything plugin does not show an entry, which is amongst the first 10 entries for the same query string in Everything itself. Thus I have to type more letters, which is inconvenient. And as the result is not listed in the list in Flow Launcher, I cannot make use of the "Set topmost for this query" feature.

Currently it is related to a file with the name "SAP.lnk". I want it to show up in FlowLauncher, when typing "SAP". But I have to type "SAP ln" so that it even shows up in the search results.

Why is it, that the search results differ between the Plugin and Everything itself? Is there something I could configure to make the desired file show up more easily?

Thanks very much in advance.

Windows 10
Everything: 1.4.1.1009
FlowLauncher: 1.9.1
Everything Plugin: 1.5.6

**Comment by ZainHan33** [comment]
same thing is happening for me. the return is barely showing any of the results i can get from everything. 

same versions as above

**Comment by jjw24** [comment]
Let me test it out, maybe due to how Flow does scoring(weighting of each result) with results, which will be different to actual Everything service. Can you provide me with a couple search terms I can try to replicate the difference.

**Comment by ZainHan33** [comment]
> 

*.pdf gives me maybe 30 hits in flow and 7000+ in everything

**Comment by guntern** [comment]
As written in the original post for me it is the search term "SAP" and the missing file is "SAP.lnk" on the desktop.
A similar issue occurs, when searching for "tex", when looking for LaTeX files. But this is even in everything not  quite unambiguous.

**Comment by taooceros** [comment]
I think flow's everything plugin only display the first 100 results? So some results may not appear because of the rank. We can expand this limit.

**Comment by guntern** [comment]
> I think flow's everything plugin only display the first 100 results? So some results may not appear because of the rank. We can expand this limit.

I am not sure, if increasing the limit would solve the issue. My search term "SAP" yields roughly 30k results in everything. Finding the right one, if it is burried deeply in the list, sounds not feasible. By the way: Does the plugin receive all 30k results and does the limiting on its own, or is the limit already applied by the API, when receiving the results from everything?

In my opinion there are two different ways to look into this:
1. Why is the ranking or sorting different between everything and the plugin results? Could this be aligned or solved differently so that more relevant results are included in the 100 results, which the plugin shows? (I stick to 100 for now, not checking if it is the true value)
2. Would there be an option to not just "set as topmost in this query", which needs the result to show up, but to specify a desired result for a specific query? I already tried editing `TopMostRecord.json` manually, but without the desired result. I suspect, that the desired result element would have to be within the limit of 100 to be considered at all. Maybe it could also helpt to specificy a weight for certain results so that they get to the top of the list.

But maybe there is a totally different way, then relying on everything? My usecase is, that I want to open certain files or programs, with typing only a minimal amount of characters.

**Comment by taooceros** [comment]
> Why is the ranking or sorting different between everything and the plugin results? Could this be aligned or solved differently so that more relevant results are included in the 100 results, which the plugin shows? (I stick to 100 for now, not checking if it is the true value)

You can adjust the sorting option in the setting panel. All sortoption is available in everything is allowed.

> Would there be an option to not just "set as topmost in this query", which needs the result to show up, but to specify a desired result for a specific query? I already tried editing TopMostRecord.json manually, but without the desired result. I suspect, that the desired result element would have to be within the limit of 100 to be considered at all. Maybe it could also helpt to specificy a weight for certain results so that they get to the top of the list.

We have thought of allowing user to specify a key-value part that used to map query, but haven't stablized the idea. Probably this may resolve your issue.

It will be hard to edit TopMostRecord.json because it is hashcode based (although stable hashcode). Detailed implementation can be checked in flow's source code.

**Comment by guntern** [comment]
>
> You can adjust the sorting option in the setting panel. All sortoption is available in everything is allowed.
> 

I did that already. But thanks for the hint. I tried it once more and came across the "run count" sort. And actually you can set the run count in everything. This way I actually could bump up my desired file in the list. I will try that. But it would not be very robust, because the run count appears to be tied to the filepath.

> 
> We have thought of allowing user to specify a key-value part that used to map query, but haven't stablized the idea. Probably this may resolve your issue.
> 

That would be great. Do you need input to stabilize the idea or do you have more than enough input ;-)

> It will be hard to edit TopMostRecord.json because it is hashcode based (although stable hashcode). Detailed implementation can be checked in flow's source code.

I would be eager to learn about the hashcode, because I did not see it in the json file. I mean there is a pluginID. But the same ID was there multiple times, so I suspected that this is the ID of the plugin providing the search result.

**Comment by jjw24** [comment]
Hi there, we have merged Everything plugin with the Explorer plugin, please update to the latest version of Flow and remove the standalone Everything plugin via `pm uninstall Everything`.

If this issue still persists, please open an issue in the main [Flow project](https://github.com/Flow-Launcher/Flow.Launcher).
