### ISSUE TITLE
Translation improvement (for source code) - Everything Plugin

### ISSUE THREAD

**Issue by smarquespt** [Flow-Launcher/Flow.Launcher.Plugin.Everything#49]
When working at Crowdin, I've noticed some strings that, in my opinion, could be improved.

**flowlauncher_plugin_everything_customized_tooltip**
"You can customize the opening of the containing folder by inputing the Environmental Variable or the Absolute Path of the File Explorer you want to use. It will be useful to use CMD to test whether the it is available."

I realy can't understand what "It will be useful to use CMD to test whether ***the it*** is available." 

**flowlauncher_plugin_everything_sort_by_file_list_filename**
"File List FileName"

I can't understand. Is this: The file name of a list of files? @taooceros answer at crowdin "it's everything sort option. I guess it is that everything can specify custom file list, so this sort based on that? I don't use it so not quite sure the actual meaning."

**flowlauncher_plugin_everything_installationfailed_subtitle**
"Failed to automatically install Everything service. Please manually install it from https://www.voidtools.com/Everything-1.3.4.686.x64-Setup.exe"

Maybe change this string to: "Please download and install latest release from [https://www.voidtools.com/"](https://www.voidtools.com/%22)

**Comment by jjw24** [comment]
> flowlauncher_plugin_everything_customized_tooltip
"You can customize the opening of the containing folder by inputing the Environmental Variable or the Absolute Path of the File Explorer you want to use. It will be useful to use CMD to test whether the it is available."

>I realy can't understand what "It will be useful to use CMD to test whether the it is available."

Hey sorry this is the left over string which should have been removed with the current release. I have submitted a PR to remove them.

>flowlauncher_plugin_everything_sort_by_file_list_filename
"File List FileName"

>I can't understand. Is this: The file name of a list of files? @taooceros answer at crowdin "it's everything sort option. I guess it is that everything can specify custom file list, so this sort based on that? I don't use it so not quite sure the actual meaning."

This is a sort option specific to Everything, might have to have a look at Everything's documentation to understand what sort behaviour it does exactly as I also can't tell from code or that name.

>flowlauncher_plugin_everything_installationfailed_subtitle
"Failed to automatically install Everything service. Please manually install it from https://www.voidtools.com/Everything-1.3.4.686.x64-Setup.exe"

> Maybe change this string to: "Please download and install latest release from [https://www.voidtools.com/"](https://www.voidtools.com/%22)

Yes, agree lets change it to a version non-specific string, the one you listed above is good.

**Comment by jjw24** [comment]
Hi there, we have merged Everything plugin with the Explorer plugin, please update to the latest version of Flow and remove the standalone Everything plugin via `pm uninstall Everything`.

If this issue still persists, please open an issue in the main [Flow project](https://github.com/Flow-Launcher/Flow.Launcher).
