### ISSUE TITLE
Doesn't work with Everything 1.5 

### ISSUE THREAD

**Issue by wards999** [Flow-Launcher/Flow.Launcher.Plugin.Everything#51]
I know Everything 1.5 is still an Alpha release but I'd hoped the plugin would work OK.

**Comment by taooceros** [comment]
It works. However, you needs to mark everything 1.5 without alpha.
check here https://www.voidtools.com/forum/viewtopic.php?t=9857

**Comment by wards999** [comment]
Great - I'd been hunting around the Everything forum and saw that from the command line I needed to do:

es.exe -instance 1.5a <your-search>
as per
https://www.voidtools.com/forum/viewtopic.php?f=5&t=11197&p=43612&hilit=command+line#p43612

but your suggestion deals with this problem a better way.

Thanks

**Comment by taooceros** [comment]
> Great - I'd been hunting around the Everything forum and saw that from the command line I needed to do:
> 
> es.exe -instance 1.5a as per https://www.voidtools.com/forum/viewtopic.php?f=5&t=11197&p=43612&hilit=command+line#p43612
> 
> but your suggestion deals with this problem a better way.
> 
> Thanks

Cool
