### ISSUE TITLE
FL not finding everything service

### ISSUE THREAD

**Issue by paintthinnerrage** [Flow-Launcher/Flow.Launcher.Plugin.Everything#62]
When using the everything plugin within FL I am unable to use everything search unless the process itself (or background process)is running. To be clear, by default everything runs a windowless program in the background which is separate from the service. Furthermore when I am in the plugin settings for Everything on FL it shows the error "Warning: Everything Service is not running" when the service is, in fact, running. To add further confusion when I select "Everything service is not running, click here to start it" within the launcher instead of starting any service, it opens an empty python window. See video for further insight. 
https://i.imgur.com/LOvpbP9.gif

(The blue process is the service fyi)

**Comment by mdmanurung** [comment]
I also experienced the same problem as @LegionDzn .

**Comment by jjw24** [comment]
Hi there, we have merged Everything plugin with the Explorer plugin, please update to the latest version of Flow and remove the standalone Everything plugin via `pm uninstall Everything`.

If this issue still persists, please open an issue in the main [Flow project](https://github.com/Flow-Launcher/Flow.Launcher).
