### ISSUE TITLE
Is it possible to sort Everything query results by date modified?

### ISSUE THREAD

**Issue by ghost** [Flow-Launcher/Flow.Launcher.Plugin.Everything#7]
How do I sort results by date modified?

I am aware of the dm: functions but the results with this criteria are still sorted by name. I am looking to be able to simply sort the results by most recently modified.

This is easy in the stand-alone Everything app as there are column headers but I can't find how to replicate this in FlowLauncher...

Any ideas?

**Comment by taooceros** [comment]
I have checked the api for everything sdk and it is quite possible to do that. I think we shall have an option to choose what we want to sort by.

**Comment by taooceros** [comment]
I am not personally free these day, so maybe I may not be able to finish this feature in a short time. Hope someone else can participate and finish it soon.

**Comment by taooceros** [comment]
Just take a look on that, this feature require everything version higher than 1.4.1, so at the same time we need to update the dependency.

**Comment by taooceros** [comment]
Since Flow is going to change largely in pluginAPI, and everything plugin will be greatly changed after that. I will implement this feature after Flow has released 1.8.0 because everything plugin doesn't work for the dev branch of Flow for now.

**Comment by taooceros** [comment]
Sorry for the late reply. I will work on it now.
